In [1]:
import numpy as np
import pandas as pd
import copy

In [2]:
dta = pd.read_csv('input.txt', header = None)

In [4]:
def calc_path(x, a_size):
    board = np.zeros([a_size, a_size])
    current_value = [round(a_size/2), round(a_size/2)]
    next_value = [round(a_size/2), round(a_size/2)]
    board[current_value[0], current_value[1]] = 99
    step_counter = 1
    #print(current_value)
    for c in x:
        current_value = copy.copy(next_value)
        #print(c)
        direction = c[0]
        step_len = int(c[1:])
        if direction == 'R':
            next_value[1] = current_value[1] + step_len
            board[current_value[0], current_value[1]:next_value[1] ]  = step_counter
           # print(next_value)
        if direction == 'D':
            next_value[0] = current_value[0] + step_len
            board[current_value[0]:next_value[0], next_value[1] ]  = 1
            #print(next_value)
        if direction == 'U':
            next_value[0] = current_value[0] - step_len
            board[next_value[0]:current_value[0] , next_value[1] ]  = 1
            #print(next_value)
        if direction == 'L':
            next_value[1] = current_value[1] - step_len
            board[next_value[0], next_value[1]: current_value[1]]   = 1 
            #print(next_value)
    return(board)   

In [85]:
def calc_path_len(x, a_size):
    board = np.zeros([a_size, a_size])
    current_value = [round(a_size/2), round(a_size/2)]
    next_value = [round(a_size/2), round(a_size/2)]
    board[current_value[0], current_value[1]] = 99
    step_counter = 0
    #print(current_value)
    for c in x:
        current_value = copy.copy(next_value)
        #print(c)
        direction = c[0]
        step_len = int(c[1:])
        step_inc = np.array(range(step_counter,(step_counter+step_len)))
        if direction == 'R':
            next_value[1] = current_value[1] + step_len
            board[current_value[0], current_value[1]:next_value[1] ]  = step_inc
           # print(next_value)
        if direction == 'D':
            next_value[0] = current_value[0] + step_len
            print(next_value)
            print(current_value)
            board[current_value[0]:next_value[0], next_value[1] ]  = step_inc
            #print(next_value)
        if direction == 'U':
            next_value[0] = current_value[0] - step_len
            board[next_value[0]:current_value[0] , next_value[1] ]  = step_inc[::-1]
            #print(next_value)
        if direction == 'L':
            next_value[1] = current_value[1] - step_len
            print(next_value[1])
            print(current_value[1])
            board[next_value[0], next_value[1]: current_value[1]]   = step_inc[::-1]
            #print(next_value)
        step_counter = step_counter+step_len
    return(board)        

In [93]:
calc_path_len(['U2', 'R2', 'D4', 'L3', 'U4', 'L1', 'D1'],5)

[4, 4]
[0, 4]
1
4
0
1
[1, 0]
[0, 0]


array([[16., 14.,  2.,  3.,  4.],
       [ 0., 13.,  0.,  0.,  5.],
       [ 0., 12., 99.,  0.,  6.],
       [ 0., 11.,  0.,  0.,  7.],
       [ 0., 10.,  9.,  8.,  0.]])

In [94]:
board = np.zeros([a_size, a_size])
current_value = [round(a_size/2), round(a_size/2)]
next_value = [round(a_size/2), round(a_size/2)]
board[current_value[0], current_value[1]] = 99
step_counter = 0
c = 'U2'
direction = c[0]
step_len = int(c[1:])
step_inc = np.array(range(step_counter,(step_counter+step_len)))

In [95]:
next_value[0] = current_value[0] - step_len
board[next_value[0]:current_value[0] , next_value[1] ]
step_inc[::-1]

array([1, 0])

In [99]:
board[next_value[0]:current_value[0] , next_value[1] ]

array([0., 0.])

In [86]:
b1 = calc_path_len(dta.loc[0], 15000)
b2 = calc_path_len(dta.loc[1], 15000)

7575
8491
[7449, 7575]
[7423, 7575]
[8188, 7999]
[7449, 7999]
7441
7999
[8627, 7441]
[8188, 7441]
7713
8077
[8664, 7713]
[8011, 7713]
8193
8259
[8227, 8193]
[7755, 8193]
8497
8534
[7681, 8497]
[7321, 8497]
8128
8497
[8132, 8128]
[7681, 8128]
7479
8128
[8653, 7479]
[8132, 7479]
7704
7913
6855
7704
[7758, 6855]
[6867, 6855]
6001
6855
[8053, 6477]
[7534, 6477]
5540
6477
[8493, 6262]
[7708, 6262]
5950
6262
[9442, 5950]
[8493, 5950]
[9658, 6751]
[9422, 6751]
[9978, 7571]
[9658, 7571]
7022
7571
[10609, 7022]
[9978, 7022]
6899
7824
[8900, 8411]
[8290, 8411]
[9653, 8808]
[8900, 8808]
8699
8808
9036
9353
[7774, 9036]
[7254, 9036]
8096
9036
[8624, 8096]
[7774, 8096]
[9425, 8690]
[8624, 8690]
8268
8690
9075
9151
8322
9075
8139
8322
7721
8580
7236
7721
[7046, 7236]
[6807, 7236]
[7986, 7690]
[7046, 7690]
[8690, 8379]
[7986, 8379]
[8702, 8489]
[8690, 8489]
[9115, 8859]
[8702, 8859]
8667
8859
[10094, 8667]
[9115, 8667]
[10745, 9657]
[10094, 9657]
9349
9657
[11285, 10136]
[10568, 10136]
[11105, 10392]

In [87]:
total = b1+ b2

In [88]:
crosses = np.where(total > 0)

In [89]:
np.amin(crosses)


1753

In [90]:
min(abs(crosses[0]-7500) + abs(crosses[1]-7500))

0

In [91]:
min(crosses[0])

3765

In [92]:
min(crosses[1])

1753

In [12]:
board[2:4, 2] = array[[1,11]]

NameError: name 'array' is not defined

In [6]:
a_size=5
board = np.zeros([a_size, a_size])
current_value = [round(a_size/2), round(a_size/2)]
next_value = [round(a_size/2), round(a_size/2)]
board[current_value[0], current_value[1]] = 99

In [16]:
board[1:3,1] = np.array(range(3,5))

In [17]:
board

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 0.,  4., 99.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [205]:
next_value[0] = current_value[0] + step_len
board[next_value[0]:current_value[0], current_value[1]]  = 1 

In [206]:
print(current_value)
print(next_value)

[2, 2]
[3, 2]


In [207]:
board[ next_value[0], current_value[1] ]= 1

In [208]:
board

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 99.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [169]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
current_value

[4, 3]

In [117]:
next_value

[4, 3]

In [154]:
round(5/2)

2

In [92]:
c = 'U1'

[2, 2]
U2
[0, 2]
R2
[0, 4]
D3
[3, 4]
L3
[3, 1]


array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0., 99.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [58]:
x = [1,0]
y = [3,0]

In [1]:
board[2:5,2]  = 1

NameError: name 'board' is not defined

In [191]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [70]:
z[1,:]

array([1.00000000e+000, 9.34605037e-307, 4.89527114e-307, 9.34613864e-307,
       1.33511494e-306])