In [1]:
import numpy as np
import pandas as pd
import copy

In [47]:
dta = pd.read_csv('input.txt', header = None)

In [3]:
def calc_path(x, a_size):
    board = np.zeros([a_size, a_size])
    current_value = [round(a_size/2), round(a_size/2)]
    next_value = [round(a_size/2), round(a_size/2)]
    board[current_value[0], current_value[1]] = 99
    step_counter = 1
    #print(current_value)
    for c in x:
        current_value = copy.copy(next_value)
        #print(c)
        direction = c[0]
        step_len = int(c[1:])
        if direction == 'R':
            next_value[1] = current_value[1] + step_len
            board[current_value[0], current_value[1]:next_value[1] ]  = step_counter
           # print(next_value)
        if direction == 'D':
            next_value[0] = current_value[0] + step_len
            board[current_value[0]:next_value[0], next_value[1] ]  = 1
            #print(next_value)
        if direction == 'U':
            next_value[0] = current_value[0] - step_len
            board[next_value[0]:current_value[0] , next_value[1] ]  = 1
            #print(next_value)
        if direction == 'L':
            next_value[1] = current_value[1] - step_len
            board[next_value[0], next_value[1]: current_value[1]]   = 1 
            #print(next_value)
    return(board)   

In [43]:
def calc_path_len(x, a_size):
    board = np.zeros([a_size, a_size])
    current_value = [round(a_size/2), round(a_size/2)]
    board[current_value[0], current_value[1]] = 99
    step_counter = 1
    #print(current_value)
    for c in x:
        direction = c[0]
        step_len = int(c[1:])+1
        if direction == 'R':
            for s in range(1,step_len):
                current_value[1] = current_value[1] + 1
                board_val = board[current_value[0], current_value[1] ]
                current_step_counter = np.where( board_val>0,board_val,step_counter )
                board[current_value[0], current_value[1] ]  = current_step_counter
                step_counter = step_counter + 1
           # print(next_value)
        if direction == 'D':
            for s in range(1,step_len):
                current_value[0] = current_value[0] + 1
                board_val = board[current_value[0], current_value[1] ]
                current_step_counter = np.where( board_val>0,board_val,step_counter )
                board[current_value[0], current_value[1] ]  = current_step_counter
                step_counter = step_counter + 1
            #print(next_value)
        if direction == 'U':
            for s in range(1,step_len):
                current_value[0] = current_value[0] - 1
                board_val = board[current_value[0], current_value[1] ]
                current_step_counter = np.where( board_val > 0,board_val,step_counter )
                board[current_value[0], current_value[1] ]  = current_step_counter
                step_counter = step_counter + 1
        if direction == 'L':
            for s in range(1,step_len):
                current_value[1] = current_value[1] - 1
                board_val = board[current_value[0], current_value[1] ]
                current_step_counter = np.where( board_val>0,board_val,step_counter )
                board[current_value[0], current_value[1] ]  = current_step_counter
                step_counter = step_counter + 1
            #print(next_value)
    return(board)        

In [45]:
calc_path_len(['U1', 'R2', 'D3', 'L3', 'U4', 'L1', 'D1'],11)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 14., 13.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., 15., 12.,  1.,  2.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 11., 99.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 10.,  0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  9.,  8.,  7.,  6.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [63]:
b1 = calc_path_len(dta.loc[0], 15000)
b2 = calc_path_len(dta.loc[1], 15000)

In [64]:
total = b1+ b2

In [65]:
crosses = total[np.where(b1*b2 > 0)]

In [79]:
np.sort(crosses)

array([1.98000e+02, 1.12220e+04, 1.16120e+04, 1.54500e+04, 1.66220e+04,
       1.69800e+04, 1.74360e+04, 1.87180e+04, 1.89460e+04, 1.91340e+04,
       1.92620e+04, 2.19000e+04, 2.19460e+04, 2.23940e+04, 2.98340e+04,
       4.54320e+04, 4.85160e+04, 5.04580e+04, 5.04580e+04, 5.30820e+04,
       5.33660e+04, 5.40500e+04, 5.47140e+04, 5.56380e+04, 5.56380e+04,
       5.60800e+04, 5.64620e+04, 5.65320e+04, 5.65880e+04, 5.75400e+04,
       5.84960e+04, 6.13560e+04, 6.22340e+04, 6.31380e+04, 6.40980e+04,
       6.59220e+04, 6.59220e+04, 6.76020e+04, 6.76020e+04, 7.30380e+04,
       7.30380e+04, 7.39040e+04, 7.49880e+04, 7.52420e+04, 7.60540e+04,
       7.69480e+04, 8.05680e+04, 8.05680e+04, 8.05680e+04, 8.17000e+04,
       8.22780e+04, 8.22780e+04, 8.24020e+04, 8.28200e+04, 8.30940e+04,
       8.34340e+04, 8.34340e+04, 8.50640e+04, 8.50640e+04, 8.65900e+04,
       8.71180e+04, 8.85380e+04, 8.97880e+04, 8.99620e+04, 9.10960e+04,
       9.11000e+04, 9.13600e+04, 9.13600e+04, 9.13600e+04, 9.160

In [53]:
min(crosses[0] + crosses[1])


9616

In [57]:
###  Test
t1 = calc_path_len(['R75','D30','R83','U83','L12','D49','R71','U7','L72'], 500)
t2 = calc_path_len(['U62','R66','U55','R34','D71','R55','D58','R83'], 500)
total = t1+ t2

In [62]:
total[np.where(t1*t2>0)]

array([624., 850., 726., 198., 610.])

In [59]:
crosses

(array([133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
        133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133,
        133, 133, 133, 133, 133, 133, 133, 133, 133, 134, 134, 135, 135,
        136, 136, 137, 137, 138, 138, 139, 139, 140, 140, 141, 141, 142,
        142, 143, 143, 144, 144, 145, 145, 146, 146, 147, 147, 148, 148,
        149, 149, 150, 150, 151, 151, 152, 152, 153, 153, 154, 154, 155,
        155, 156, 156, 157, 157, 158, 158, 159, 159, 160, 160, 161, 161,
        162, 162, 163, 163, 164, 164, 165, 165, 166, 166, 167, 167, 168,
        168, 169, 169, 170, 170, 171, 171, 172, 172, 173, 173, 174, 174,
        175, 175, 176, 176, 177, 177, 178, 178, 179, 179, 180, 180, 181,
        181, 182, 182, 183, 183, 184, 184, 185, 185, 186, 186, 187, 187,
        188, 188, 188, 188, 188, 188, 188, 188, 188, 188, 188, 188, 188,
        188, 188, 188, 188, 188, 188, 188, 188, 188, 188, 188, 188, 188,
        188, 188, 188, 188, 188, 188, 188, 188, 188

In [92]:
min(crosses[1])

1753

In [12]:
board[2:4, 2] = array[[1,11]]

NameError: name 'array' is not defined

In [6]:
a_size=5
board = np.zeros([a_size, a_size])
current_value = [round(a_size/2), round(a_size/2)]
next_value = [round(a_size/2), round(a_size/2)]
board[current_value[0], current_value[1]] = 99

In [16]:
board[1:3,1] = np.array(range(3,5))

In [17]:
board

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 0.,  4., 99.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [205]:
next_value[0] = current_value[0] + step_len
board[next_value[0]:current_value[0], current_value[1]]  = 1 

In [206]:
print(current_value)
print(next_value)

[2, 2]
[3, 2]


In [207]:
board[ next_value[0], current_value[1] ]= 1

In [208]:
board

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 99.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [169]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
current_value

[4, 3]

In [117]:
next_value

[4, 3]

In [154]:
round(5/2)

2

In [92]:
c = 'U1'

[2, 2]
U2
[0, 2]
R2
[0, 4]
D3
[3, 4]
L3
[3, 1]


array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0., 99.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [58]:
x = [1,0]
y = [3,0]

In [1]:
board[2:5,2]  = 1

NameError: name 'board' is not defined

In [191]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [70]:
z[1,:]

array([1.00000000e+000, 9.34605037e-307, 4.89527114e-307, 9.34613864e-307,
       1.33511494e-306])