In [3]:
import numpy as np
import pandas as pd
import copy

In [2]:
dta = pd.read_csv('input.txt', header = None)

In [10]:
#dta.loc[0]

In [15]:
def calc_path(x, a_size):
    board = np.zeros([a_size, a_size])
    current_value = [round(a_size/2), round(a_size/2)]
    next_value = [round(a_size/2), round(a_size/2)]
    board[current_value[0], current_value[1]] = 99
    step_counter = 1
    #print(current_value)
    for c in x:
        current_value = copy.copy(next_value)
        #print(c)
        direction = c[0]
        step_len = int(c[1:])
        if direction == 'R':
            next_value[1] = current_value[1] + step_len
            board[current_value[0], current_value[1]:next_value[1] ]  = step_counter
           # print(next_value)
        if direction == 'D':
            next_value[0] = current_value[0] + step_len
            board[current_value[0]:next_value[0], next_value[1] ]  = 1
            #print(next_value)
        if direction == 'U':
            next_value[0] = current_value[0] - step_len
            board[next_value[0]:current_value[0] , next_value[1] ]  = 1
            #print(next_value)
        if direction == 'L':
            next_value[1] = current_value[1] - step_len
            board[next_value[0], next_value[1]: current_value[1]]   = 1 
            #print(next_value)
    return(board)        

In [16]:
calc_path(['U2', 'R2', 'D3', 'L3'],5)

array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0., 99.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
b1 = calc_path(dta.loc[0], 15000)
b2 = calc_path(dta.loc[1], 15000)

In [19]:
total = b1+ b2

In [21]:
crosses = np.where(total == 2)

In [25]:
round(15000/2)


7500

In [27]:
min(abs(crosses[0]-7500) + abs(crosses[1]-7500))

303

In [23]:
crosses[0]

array([ 5743,  5743,  5743,  5774,  5811,  6048,  6094,  6149,  6149,
        6152,  6330,  6342,  6369,  6442,  6447,  6447,  6448,  6621,
        6672,  6867,  6892,  6892,  6991,  7038,  7046,  7175,  7244,
        7254,  7254,  7339,  7412,  7423,  7449,  7500,  7500,  7500,
        7652,  7652,  7652,  7679,  7679,  7679,  7681,  7686,  7695,
        7726,  7736,  7736,  7736,  7736,  7774,  7803,  7803,  7803,
        7803,  7803,  7803,  7837,  7858,  7858,  7872,  7898,  7955,
        7965,  7986,  7986,  7986,  8011,  8011,  8053,  8065,  8065,
        8065,  8065,  8069,  8069,  8069,  8132,  8132,  8162,  8188,
        8205,  8205,  8205,  8227,  8276,  8286,  8286,  8290,  8290,
        8290,  8302,  8302,  8302,  8346,  8346,  8346,  8346,  8346,
        8357,  8494,  8535,  8558,  8561,  8624,  8624,  8626,  8626,
        8627,  8627,  8637,  8660,  8660,  8660,  8660,  8660,  8660,
        8660,  8664,  8664,  8729,  8729,  8768,  8820,  8859,  8859,
        8900,  8925,

In [12]:
board[2:4, 2] = array[[1,11]]

NameError: name 'array' is not defined

In [4]:
a_size=5
board = np.zeros([a_size, a_size])
current_value = [round(a_size/2), round(a_size/2)]
next_value = [round(a_size/2), round(a_size/2)]
board[current_value[0], current_value[1]] = 99

In [204]:
direction = c[0]
step_len = int(c[1:])

In [205]:
next_value[0] = current_value[0] + step_len
board[next_value[0]:current_value[0], current_value[1]]  = 1 

In [206]:
print(current_value)
print(next_value)

[2, 2]
[3, 2]


In [207]:
board[ next_value[0], current_value[1] ]= 1

In [208]:
board

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 99.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [169]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
current_value

[4, 3]

In [117]:
next_value

[4, 3]

In [154]:
round(5/2)

2

In [92]:
c = 'U1'

[2, 2]
U2
[0, 2]
R2
[0, 4]
D3
[3, 4]
L3
[3, 1]


array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0., 99.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [58]:
x = [1,0]
y = [3,0]

In [1]:
board[2:5,2]  = 1

NameError: name 'board' is not defined

In [191]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [70]:
z[1,:]

array([1.00000000e+000, 9.34605037e-307, 4.89527114e-307, 9.34613864e-307,
       1.33511494e-306])