In [216]:
import numpy as np
import pandas as pd
import copy

In [19]:
dta = pd.read_csv('input.txt', header = None)

In [20]:
dta

0     1     2     3     4     5     6     7     8     9    ...    291  \
0  R991   U77  L916   D26  R424  D739  L558  D439  R636  U616  ...   D143   
1  L997  U989  L596  U821  L419  U118  R258  D239  R902  D810  ...   U696   

    292   293   294   295   296   297   298   299   300  
0  L176  U673  L772   D93   L10  D624  L244  D993  R346  
1  R248  D746  R990  U829  R812  U294  L462  U740  R780  

[2 rows x 301 columns]

In [241]:
def calc_path(x, a_size):
    board = np.zeros([a_size, a_size])
    current_value = [round(a_size/2), round(a_size/2)]
    next_value = [round(a_size/2), round(a_size/2)]
    board[current_value[0], current_value[1]] = 99
    print(current_value)
    for c in x:
        current_value = copy.copy(next_value)
        print(c)
        direction = c[0]
        step_len = int(c[1:])
        if direction == 'R':
            next_value[1] = current_value[1] + step_len
            board[current_value[0], current_value[1]:next_value[1] ]  = 1
            print(next_value)
        if direction == 'D':
            next_value[0] = current_value[0] + step_len
            board[current_value[0]:next_value[0], current_value[1] ]  = 1
            print(next_value)
        if direction == 'U':
            next_value[0] = current_value[0] - step_len
            board[next_value[0]:current_value[0] , current_value[1] ]  = 1
            print(next_value)
        if direction == 'L':
            next_value[1] = current_value[1] - step_len
            board[current_value[0], next_value[1]: current_value[1]]   = 1 
            print(next_value)
    return(board)        

In [203]:
a_size=5
board = np.zeros([a_size, a_size])
current_value = [round(a_size/2), round(a_size/2)]
next_value = [round(a_size/2), round(a_size/2)]
board[current_value[0], current_value[1]] = 99

In [204]:
direction = c[0]
step_len = int(c[1:])

In [205]:
next_value[0] = current_value[0] + step_len
board[next_value[0]:current_value[0], current_value[1]]  = 1 

In [206]:
print(current_value)
print(next_value)

[2, 2]
[3, 2]


In [207]:
board[ next_value[0], current_value[1] ]= 1

In [208]:
board

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 99.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [169]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
current_value

[4, 3]

In [117]:
next_value

[4, 3]

In [154]:
round(5/2)

2

In [92]:
c = 'U1'

In [242]:
calc_path(['U2', 'R2', 'D3', 'L3'],5)

[2, 2]
U2
[0, 2]
R2
[0, 4]
D3
[3, 4]
L3
[3, 1]


array([[ 0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  0.,  1.],
       [ 0.,  0., 99.,  0.,  1.],
       [ 0.,  1.,  1.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [58]:
x = [1,0]
y = [3,0]

In [190]:
board[2:5,2]  = 1

In [191]:
board

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [70]:
z[1,:]

array([1.00000000e+000, 9.34605037e-307, 4.89527114e-307, 9.34613864e-307,
       1.33511494e-306])